### ISSUE TITLE
Pure Java client for Centrifugo

### ISSUE THREAD

**Issue by donald-jackson** [centrifugal/documentation#20]
Hi there,

If anyone is interested, I have created a pure Java client for Centrifugo, forked from the Android client and just removed some specific Android code (so not much work...)

https://github.com/donald-jackson/centrifuge-java

Thanks
Donald

**Comment by FZambia** [comment]
@donald-jackson hello! Great to see efforts like this - thanks! 

Could you send pull request with link to your client into this section of docs: https://fzambia.gitbooks.io/centrifugal/content/clients/mobile_and_other.html ?

**Comment by FZambia** [comment]
@donald-jackson thanks again for sharing your work. Take a look at Centrifugo v2 btw:)

**Comment by donald-jackson** [comment]
@FZambia cool will do, when its ready I'll patch for new version :)
